package iThink.Automation.utils;

public enum DateRangeType {
	
	SAME_MONTH_CURRENT_YEAR,
	SAME_MONTH_PREVIOUS_YEAR,
	CROSS_MONTH_SAME_YEAR,
	CROSS_YEAR_WITHIN_ONE_YEAR,
	CROSS_YEAR_OVER_ONE_YEAR,
	FUTURE_DATE
}
